language: python
python:
- '3.9'
sudo: false
cache:
  directories:
  - "~/.platformio"
  - "$HOME/.cache/pip"
install:
- pip install -U platformio
- pio update
script:
- export PROG_VERSION=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- pio run
before_deploy:
- pio run -e d1_mini -c platformio.ini
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ".pio/build/d1_mini/firmware.bin"
  skip_cleanup: true
  on:
    tags: true
